;Configuration for the main check.
[CHECK]
HOST=https://download.pinglite.xyz ;The target you are checking.

[VALIDATION]
RETURNCODE=200 ;What you are expecting as a return code.

SSLVALID=1 ;Weather to report failure if SSL certificate is invalid or nonexistant.
; 0 - Do not report if SSL is invalid.
; 0 - Do not report if SSL cert is nonexistant (http).
; 1 - Report if SSL cert is invalid or nonexistant (http).

SSLEXPIRYREMINDER=30 ;How many days before SSL expiry to notify. (https only)


[REPORTING]
METHOD=NONE
; Options as follows, more to be added in the future.
; ---------------------------------------------------
; NONE    - STDOUT only. - DEFAULT
; RETCODE - Returns 1 on failure of program or validation. See STDOUT and STDERR for reason.
; 



;-----UNUSED AS OF YET-----
;SSLEXPIRYSNOOZE=1 ;How many days after previous alert to remind you SSL cert is expiring soon.
; Reverts to standard alert once expires.

;ALERTSNOOZE=30 ;How many minutes after previous alert to wait before alerting again. 