// Object to handle recordkeeping.

#include <iostream>
#include <fstream>
#include <string>
#include <sstream>
#include <ctime>
#include <stdexcept>
#include "record.hpp"
#include "function.hpp"
#include "../third-party/inih/cpp/INIReader.h"

//Constructor
//Takes in a filename, parses the file, and saves data to the object.
record::record(std::string filename) {
	this->FILENAME = filename;
	
	//Read file, if it exists. If not exist, place default data.
	INIReader reader(this->FILENAME);

	this->CODEEXPECTED = reader.GetBoolean(this->HEADER, "CODEEXPECTED", true);
	this->SSLVALID = reader.GetBoolean(this->HEADER, "SSLVALID", true);
	this->SSLWARNING = reader.GetBoolean(this->HEADER, "SSLWARNING", false);
	this->DOWNSINCE = record::stringToLongLong(reader.Get(this->HEADER, "DOWNSINCE", "0"));
	this->LASTALERT = record::stringToLongLong(reader.Get(this->HEADER, "LASTALERT", "0"));
	this->LASTSSLWARNING = record::stringToLongLong(reader.Get(this->HEADER, "LASTSSLWARNING", "0"));

	//bool CODEEXPECTED = true;  //Is the previous code as expected.
	//bool SSLVALID = true;      //Is the SSL cert valid.
	//bool SSLWARNING = false;   //Is the SSL cert warning for expiry.
	//int DOWNSINCE = 0;         //Timestamp of first down. ------------ 0 for still up.
	//int LASTALERT = 0;         //Timestamp of last alert. ------------ 0 for still up.
	//int LASTSSLWARNING = 0;    //Timestamp of last SSL expiry alert. - 0 for no alert needed.

}

// Takes in the new data in the form of bool.
// Returns true if data is the same as previous.
// Returns false if any information is changed from previous.
void record::update(bool codeexpected, bool sslvalid, bool sslwarning) {
	this->NEWCODEEXPECTED = codeexpected;
	this->NEWSSLVALID = sslvalid;
	this->NEWSSLWARNING = sslwarning;
	this->NOW = static_cast<long long int>(std::time(nullptr));

	if (this->NEWCODEEXPECTED == this->CODEEXPECTED) { this->CODECHANGE = false; }
	else { this->CODECHANGE = true; }

	if (this->NEWSSLVALID == this->SSLVALID) { this->SSLVALIDCHANGE = false; }
	else { this->SSLVALIDCHANGE = true; }

	if (this->NEWSSLWARNING == this->SSLWARNING) { this->SSLWARNCHANGE = false; }
	else { this->SSLWARNCHANGE = true; }
}

int record::write() {
	this->CODEEXPECTED = this->NEWCODEEXPECTED;
	this->SSLVALID = this->NEWSSLVALID;
	this->SSLWARNING = this->NEWSSLWARNING;

	if (this->CODEEXPECTED) { this->DOWNSINCE = 0; this->LASTALERT = 0; }
	if (not this->SSLWARNING) { this->LASTSSLWARNING = 0; }

	//Write all the data to the file.
	std::ofstream outputFile(this->FILENAME); // Open the file for writing.

	if (not outputFile.is_open()) {
		std::cerr << "Record file could not be opened for writing!" << std::endl;
		return 1;
	}

	outputFile << "; This file is automatically generated/updated." << std::endl;
	outputFile << "; Manual updates are discouraged!" << std::endl;
	outputFile << "[" << this->HEADER << "]" << std::endl;
	outputFile << "CODEEXPECTED=" << function::stringifyBoolean(this->CODEEXPECTED) << std::endl;
	outputFile << "SSLVALID=" << function::stringifyBoolean(this->SSLVALID) << std::endl;
	outputFile << "SSLWARNING=" << function::stringifyBoolean(this->SSLWARNING) << std::endl;
	outputFile << "DOWNSINCE=" << this->DOWNSINCE << std::endl;
	outputFile << "LASTALERT=" << this->LASTALERT << std::endl;
	outputFile << "LASTSSLWARNING=" << this->LASTSSLWARNING << std::endl;

	outputFile.close(); //Close the file.

	std::cout << "File has been written to and closed." << std::endl;
	return 0;
}

bool record::alertRequired(int SSLEXPIRYSNOOZE, int ALERTSNOOZE)
{
	bool isRequired = false;

	//Checks Site Codes
	if (this->NEWCODEEXPECTED and this->CODECHANGE) {
		isRequired = true;
		this->ALERTSTRING += "Recovery: Site is now returning the correct code.\n";
	}
	else if (not this->NEWCODEEXPECTED and this->isAlertSnoozeExpired(ALERTSNOOZE)) {
		isRequired = true;
		this->ALERTSTRING += "ERROR: Site Is Returning Incorrect Code!\n";
		this->LASTALERT = this->NOW;
		if (this->CODECHANGE and this->DOWNSINCE == 0) { this->DOWNSINCE = this->NOW; }
	}

	//Checks SSL Certificate Validity
	if (this->NEWSSLVALID and this->SSLVALIDCHANGE) {
		isRequired = true;
		this->ALERTSTRING += "Recovery: SSL Certificate is now valid.\n";
	}
	else if (not this->NEWSSLVALID and this->isAlertSnoozeExpired(ALERTSNOOZE)) {
		isRequired = true;
		this->ALERTSTRING += "ERROR: SSL Certificate is Invalid!\n";
		this->LASTALERT = this->NOW;
		if (this->SSLVALIDCHANGE and this->DOWNSINCE == 0) { this->DOWNSINCE = this->NOW; }
	}

	//Checks SSL Warning Status
	if (this->NEWSSLWARNING and this->SSLWARNCHANGE) {
		isRequired = true;
		this->ALERTSTRING += "Recovery: SSL Certificate has been renewed.\n";
	}
	else if (not this->NEWSSLWARNING and this->isWarnSnoozeExpired(SSLEXPIRYSNOOZE)) {
		isRequired = true;
		this->ALERTSTRING += "WARNING: SSL Certificate will be expiring soon!\n";
		if (this->SSLWARNCHANGE) { this->LASTSSLWARNING = this->NOW; }
	}
	return isRequired;
}

std::string record::alertText()
{
	return this->ALERTSTRING;
}




//Get statements for private variables.
bool record::getCODECHANGE() { return this->CODECHANGE; }
bool record::getSSLVALIDCHANGE() { return this->SSLVALIDCHANGE; }
bool record::getSSLWARNCHANGE() { return this->SSLWARNCHANGE; }
int record::getDOWNSINCE() { return this->DOWNSINCE; }
int record::getLASTALERT() { return this->LASTALERT; }
int record::getLASTSSLWARNING() { return this->LASTSSLWARNING; }

//Convert a string of numbers to a long long int.
long long record::stringToLongLong(const std::string& str)
{
	long long result = 0;
	std::stringstream ss(str);

	if (ss >> result) {
		// Check if there are any remaining characters after the number
		char remaining;
		if (ss >> remaining) {
			// String contains non-numeric characters after the number
			throw std::invalid_argument("String contains non-numeric characters.");
		}
		return result;
	}
	else {
		// String is not a valid number
		throw std::invalid_argument("Invalid number string.");
	}
}

//Int snooze in minutes.
bool record::isAlertSnoozeExpired(int SNOOZE)
{
	return this->isSnoozeExpired(SNOOZE * 60, this->LASTALERT);
}

//Int snooze in days.
bool record::isWarnSnoozeExpired(int SNOOZE)
{
	return this->isSnoozeExpired(SNOOZE * 24 * 60 * 60, this->LASTSSLWARNING);
}

//Int snooze in seconds, long long last is time to compare to of last alert.
bool record::isSnoozeExpired(int SNOOZE, long long LAST)
{
	long long snoozeLong = static_cast<long long>(SNOOZE);
	long long differenceSeconds = this->NOW - LAST;
	return differenceSeconds > snoozeLong;
}

//Destructor
record::~record() {}
